
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - xclip
        - lxsession
        - volumeicon
        - rclone
        - caprine
        - rofi-emoji
        - rofi-calc
        - libqalculate
        - pacman-contrib
        - vim
        - alacritty
        - conky
        - starship
        - ranger
        - exa
        - gparted
        - okular
        - vlc
        - code
        - dolphin
        - dunst
        - neofetch
        - libreoffice-fresh
        - gparted
        - qbittorrent
        - thunderbird
        - nitrogen
        - feh
        - tmux
        - cronie
        - openssh
        - xterm
        - dmenu
        - rofi
        - firefox
        - i3
        - i3blocks
        - network-manager-applet
        - blueberry
        - acpi
        - python3
        - i3lock
        - qtile
        - python-dbus-next
        - tigervnc
        - neovim
        - nodejs
        - npm
        - zsh
        - ttf-font-awesome
        - otf-font-awesome
        - ttf-sourcecodepro-nerd
        - ttf-ubuntu-font-family
        - ttf-mononoki-nerd
        - lxappearance
        - xdotool
        - picom

  - name: Start SSHD
    service:
      name: sshd
      state: started
      enabled: yes

  - name: Start cronie.service
    service:
      name: cronie
      state: started
      enabled: yes

  - name: Start bluetooth.service
    service:
      name: bluetooth.service
      state: started
      enabled: yes

  - name: Copy alacritty
    copy:
      src: files/alacritty
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy Bashrc
    copy:
      src: files/bashrc
      dest: /home/fred/.bashrc
      owner: fred
      group: fred

  - name: Copy Conky
    copy:
      src: files/conky
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy i3
    copy:
      src: files/i3
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy onedrive
    copy:
      src: files/onedrive
      dest: /home/Documents
      owner: fred
      group: fred
      mode: a+x

  - name: Copy picom
    copy:
      src: files/picom
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy power.rasi
    copy:
      src: files/rofi/power.rasi
      dest: /home/fred/rofi
      owner: fred
      group: fred

  - name: Copy powermenu
    copy:
      src: files/powermenu
      dest: /home/fred/.local/bin
      owner: fred
      group: fred
      mode: a+x

  - name: Copy qtile
    copy:
      src: files/qtile
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy rofi
    copy:
      src: files/rofi
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy tmux.conf
    copy:
      src: files/tmux.conf
      dest: /home/fred/.config
      owner: fred
      group: fred

  - name: Copy vnc
    copy:
      src: files/vnc
      dest: /home/fred/.vnc
      owner: fred
      group: fred

  - name: Copy wallpapers
    copy:
      src: files/wallpapers
      dest: /home/fred
      owner: fred
      group: fred

  - name: Copy wifimenu
    copy:
      src: files/wifimenu
      dest: /home/fred/.local/bin
      owner: fred
      group: fred
      mode: a+x

  - name: execute arch-update
    file:
      dest: /home/fred/.config/i3/scripts/arch-update
      mode: a+x

  - name: execute battery2
    file:
      dest: /home/fred/.config/i3/scripts/battery2
      mode: a+x

  - name: execute calendar
    file:
      dest: /home/fred/.config/i3/scripts/calendar
      mode: a+x

  - name: execute disk
    file:
      dest: /home/fred/.config/i3/scripts/disk
      mode: a+x

  - name: execute memory
    file:
      dest: /home/fred/.config/i3/scripts/memory
      mode: a+x

  - name: execute spotify.py
    file:
      dest: /home/fred/.config/i3/scripts/spotify.py
      mode: a+x

  - name: execute volume
    file:
      dest: /home/fred/.config/i3/scripts/volume
      mode: a+x

  - name: execute qtile autostart.sh
    file:
      dest: /home/fred/.config/qtile/autostart.sh
      mode: a+x

  - name: Add ansible user
    user:
      name: velociraptor
      system: yes

  - name: Set up sudo for ansible user
    copy:
      src: files/sudoer_velociraptor
      dest: /etc/sudoers.d/velociraptor
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: Ansible auto-provision
      user: velociraptor
      minute: "*/1"
      job: ansible-pull -o -U https://github.com/rider48371/ansible_laptop.git
